### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#10]
Hi

Updated to latest nuget, and trying to do this code:

         ```
            var httpClient = new HttpClient { BaseAddress = ScryfallApiClientConfig.GetDefault().ScryfallApiBaseAddress };
            var scryfallApiClient = new ScryfallApiClient(httpClient);

            Card randomCard = scryfallApiClient.Cards.GetRandom().Result;
```

This GetRandom() worked in the previous nuget, now I get this error when calling GetRandom():

System.AggregateException
  HResult=0x80131500
  Message=Er zijn één of meer fouten opgetreden.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Magic_The_Gathering_Collector.RandomCardForm.DisplayRandomCard() in F:\Visual Studio project\Magic The Gathering Collector\Magic The Gathering Collector\RandomCardForm.cs:line 41
   at Magic_The_Gathering_Collector.RandomCardForm..ctor() in F:\Visual Studio project\Magic The Gathering Collector\Magic The Gathering Collector\RandomCardForm.cs:line 33
   at Magic_The_Gathering_Collector.MainForm..ctor() in F:\Visual Studio project\Magic The Gathering Collector\Magic The Gathering Collector\MainForm.cs:line 76
   at Magic_The_Gathering_Collector.Program.Main() in F:\Visual Studio project\Magic The Gathering Collector\Magic The Gathering Collector\Program.cs:line 19

  This exception was originally thrown at this call stack:
    System.Number.StringToNumber(string, System.Globalization.NumberStyles, ref System.Number.NumberBuffer, System.Globalization.NumberFormatInfo, bool)
    System.Number.ParseDecimal(string, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
    ScryfallApi.Client.DecimalAsStringConverter.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    ...
    [Call Stack Truncated]

Inner Exception 1:
FormatException: De indeling van de invoertekenreeks is onjuist.

**Comment by ghost** [comment]
PS: the nuget package installation was successfull!

Is it normal not all variables of for example a Card instance have comments?
I see comments but some variables don't display comments while others do.

thx

**Comment by ghost** [comment]
I have exactly the same exception when doing scryfallApiClient.Cards.GetRandom().Result

I use .NET Framework 4.8 and I use latest nuget package.

Can you look at it?

**Comment by Gonkers** [comment]
I will take a look at it tonight and attempt to get a fix out quickly. I really do need to add some unit testing, but that won’t be tonight.

It looks like it’s a problem with the JSON coming from scryfall. The switch to using System.Text.Json from Json.net is painful. The new library is very strictly following the JSON spec, where Json.net works around invalid JSON

**Comment by Gonkers** [comment]
I cannot replicate the issue using the sample .NET Framework console app. Do you by chance know what card triggered the error? I assume it's a subset of cards.  Oh, or it could possibly be number formats. What language do you have set as your default language in windows?

**Comment by Gonkers** [comment]
I have pushed a fix for the deserialization issue. I'm pretty sure it had to do with non-US culture when parsing `1.23` (vs `1,23`).

**Comment by ghost** [comment]
It's fixed, thx a lot!!!!!!!!!
