### ISSUE TITLE
ScryfallAPI for .NET 4 and .NET 5 ?

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#13]
Hi

When trying to install the nuget package ScryfallAPI.Client 3.1.0 in a .NET 4 project I get the following error:

Error		Could not install package 'ScryfallAPI.Client 3.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

Is it possible to make the package compatible with .NET 4 and .NET 5 too?

**Comment by Gonkers** [comment]
I won't be making a build targeting .NET 5 as its [end of life is imminent](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

I will also not target "classic" .NET Framework 4.x or lower. However I will look into targeting .NET Standard, but I cannot make any promises.

Thanks for the questions

**Comment by ghost** [comment]
Hi

Can I use a .NET Standard package in .NET 4 and .NET 5 too? Not everybody is using .NET 6.
I especially use .NET 4 because some packages I use are not converted to .NET 6 (or even 5). :-(

Lisa

**Comment by Gonkers** [comment]
You should be able to yes.

**Comment by ThatOhio** [comment]
Just wanted to chime in on this thread for anyone who comes across it, nothing in this library is incompatible with .net standard, so if you wanted to do it yourself you'd just need to change the target framework in the project file, and I think I might have needed to add one more package, but none of the code itself needed to change, very easy conversion.

**Comment by Gonkers** [comment]
I'm finally getting back to updating this library. With the latest incoming changes, it will not be compatible with versions older than `net6.0`.  The new version is using [init](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init) and [DateOnly](https://learn.microsoft.com/en-us/dotnet/api/system.dateonly)
