### ISSUE TITLE
Missing Price data - update frequency?

### ISSUE THREAD

**Issue by Sigurdur42** [Gonkers/Scryfall-API-Client#3]
Hi,
I just detected (and fixed) the wrong price information.
Do you have any plans to update the nuget package on a more regular base? 
Thx
Michael

**Comment by Gonkers** [comment]
This is a pet project that I don't use very often, hence why I didn't notice the price structure change in the API. But I will gladly accept pull requests like the one you submitted. I'll try to get to #2 shortly.

**Comment by Gonkers** [comment]
Your bug fix has been [released](https://github.com/Gonkers/Scryfall-API-Client/releases/tag/1.0.4)! It has been published to nuget and should show up in the search index soon.
