### ISSUE TITLE
Examples or docs?

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#5]
Hi

Is it possible to make an 'examples' folder that has some files showing beginners like me the basic usage of the library (for a C# application)?

For example:

- how to get all sets and their information
- how to get card info for each card in a set
- how to execute the various queries possible on scryfall and how to get the search results back using your library

Because there are no api docs on github, providing some examples would be great!

Thanks in advance!

**Comment by Gonkers** [comment]
Sure thing. I'll see what I can do today.

**Comment by Gonkers** [comment]
I have a new update in progress. I've made some changes, but they are not merged into the main branch yet. You can preview them here https://github.com/Gonkers/Scryfall-API-Client/tree/dotnet5

**Comment by ghost** [comment]
It's now much easier to initialize the client, thanks! I understand it now.

If possible, could you also provide examples of the 3 things I asked in my first message here?

Thanks a lot!
Jessica

PS: nice ASCII art! ;-)

**Comment by Gonkers** [comment]
I have added some more examples, and merged my changes into the main branch.
[Retrieving sets](https://github.com/Gonkers/Scryfall-API-Client/blob/master/samples/ScryfallApi.WebSample/Pages/Sets.cshtml.cs)
[Querying/Getting cards by set](https://github.com/Gonkers/Scryfall-API-Client/blob/master/samples/ScryfallApi.WebSample/Pages/Cards.cshtml.cs#L33)

**Comment by ghost** [comment]
I think those are web examples?
The retrieving sets I understand but the getting cards I can't transform for a C# program (.NET Framework).
Would it be possible to give an example how to do this?

PS: I'm a C# beginner

Jessica

**Comment by Gonkers** [comment]
Well I'm glad you're trying out new languages! Welcome to the community.  If you're on Twitter, [Scott Hanselman](https://twitter.com/shanselman/) and [Maria Naggaga](https://twitter.com/LadyNaggaga) good people to follow for some beginner c# gems. If you haven't found this site (https://dotnet.microsoft.com/platform/try-dotnet) yet, it can be pretty useful too.

As far as the examples go, the web and console app samples use the same library and are used in the same way. I don't attempt to make the scryfall API easier to use, I just expose the same API surface that if you were to use the site directly. 

So to search for all creature cards that have something to do with drawing cards, you'd search with the query [`o:draw t:creature` ](https://scryfall.com/search?q=o:draw%20t:creature). To do the same with this .NET client you would run the following...
```c#
var results = await client.Cards.Search(query:"o:draw t:creature", page:1, sort:SearchOptions.CardSort.Name);
```
The search syntax can be found on their site here https://scryfall.com/docs/syntax
