### ISSUE TITLE
creating a ScryfallApiClient 

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#6]
Hi

The constructor of ScryfallApiClient is as following:

`public ScryfallApiClient(HttpClient httpClient, ILogger<ScryfallApiClient> logger, IMemoryCache cache = null)`

How to created a logger for the 2nd parameter?
I don't find any code example and I'm not sure how to do it.

thx

**Comment by Gonkers** [comment]
Typically that would be setup for you with the .NET Core dependency injection. I will make some additional documentation or some additional constructors to make it easier to use. Stay tuned!

**Comment by ghost** [comment]
I'm not using .NET Core but .NET Framework.
I hope the library supports .NET Framework too!

Thank you very much!

Jessica

**Comment by Gonkers** [comment]
This library fully supports .NET Framework and have updated the constructor to make it easier to use when not using dependency injection. See [this](https://github.com/Gonkers/Scryfall-API-Client/blob/master/samples/ScryfallApi.NetFxExample/Program.cs#L14) example.
