### ISSUE TITLE
Card Colors property

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#7]
Hi

I don't see the comments in visual studio when selecting a property from for example a Card.
Is it maybe possible to show comments in visual studio?

A Card has a Colors property which is a string array.
Is the most important color in array index 0 or how to understand this?

I tried it on some cards and I think it uses "B" for black but also for blue.
I'm not 100% sure. 
Is this a bug?

thx

**Comment by ghost** [comment]
So basically I need documentation or visual studio comments (for some reason they don't appear here after installing with nuget) to understand what all variables/methods are doing.

Thanks for all the work on the library!

**Comment by ghost** [comment]
I had the same problem with another library: visual studio comments didn't appear when using nuget package but they did appear when copying all source code files of the library into my project.
The developer of that library thought it could be caused by the nuget package not built correctly.
There is no solution yet, but I just want to let you know this because I think the same problem is in your library too.

Here is the similar issue of that other library:

https://github.com/MagicTheGathering/mtg-sdk-dotnet/issues/32

Did you try if you see the visual studio comments when using only the nuget package?

thx in advance!

**Comment by ghost** [comment]
On google I found a possible solution for this issue. Note I never made any nuget package myself, I just show you this link because I believe this is the solution.

https://stackoverflow.com/questions/40110687/intellisense-and-triple-slash-comments-in-packages

**Comment by Gonkers** [comment]
Thanks for the info! I'll take a closer look.
