### ISSUE TITLE
question: .NET 5

### ISSUE THREAD

**Issue by ghost** [Gonkers/Scryfall-API-Client#9]
Hi

I'm starting  .NET 5 coding here and I was wondering if you plan to make a nuget package for .NET 5 too?

thx in advance!

**Comment by ghost** [comment]
If possible I would love to have a nuget package that can target .Net Framework 4 and also the new .Net 5.0.
Or 2 packages if it can't be done in 1.

If it's not asked too much

Thanks in advance!
Jessica

**Comment by ghost** [comment]
do you still read this?

**Comment by Gonkers** [comment]
Yes. The nuget package supports net4.7 and netstandard 2.0 which works with
 .net 5. It’s a busy weekend. ;-)
